name: Deploy to WordPress.org SVN

on:
  release:
    types: [released] # Se déclenche lorsque vous créez une "Release" sur GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Remove extended folder and GitHub readme
      run: |
        rm -rf extended
        rm -f readme.md

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: quora-importer
